### ISSUE TITLE
Support streaming the sitemap

### ISSUE THREAD

**Issue by rudolfbyker** [nuxt-modules/sitemap#143]
### Details

I'm using `defineEventHandler` in `/server/api/_sitemap-urls.ts` in my project to query our Apache Solr search engine to determine what should be shown in the sitemap, something like this:

```ts
export default defineEventHandler(async (): Promise<SitemapEntry[]> => {
  const solrClient = new SolrClient(...);

  // TODO: What if this becomes too big to hold in memory?
  const entries: SitemapEntry[] = [
    ...solrClient.getFoo().map(foo => {loc: '...', lastmod: '...'}),
    ...solrClient.getBar().map(bar => {loc: '...', lastmod: '...'}),
  ];
});
```

The number of items are growing rapidly, and soon we will have trouble keeping all of them in memory. It would be nice if I could use an async generator to yield `SitemapEntry` items one by one, and have `nuxt-simple-sitemap` consume them as needed, streaming them directly to disk or to HTTP Response.

Is this possible yet?

The [`sitemap`](https://www.npmjs.com/package/sitemap) npm package has a [`SitemapAndIndexStream`](https://github.com/ekalinin/sitemap.js/blob/HEAD/api.md#sitemapandindexstream) class for situations like this.

**Comment by harlan-zw** [comment]
Hey @rudolfbyker, thanks for the issue.

I think this is a great idea to support this type of functionality. Unfortunately, it will require quite a bit of work on my end so I'll need to park this until I have more time.

If more people need this feature it will get prioritised.

**Comment by dapzer** [comment]
We need it

**Comment by harlan-zw** [comment]
Having investigated the implementation for this I think I'm going to descope this. It adds too much complexity and breaks too much internal logic, while there is a fairly simple work around available.

For example, if I enable this then:
- many of the i18n features will break, such as automatic alternatives
- we can't sort the entries
- breaks existing hooks, wouldn't be possible to do `sitemap:output`

The workaround is to use [multi sitemaps](https://nuxtseo.com/sitemap/guides/multi-sitemaps) with [custom sources](https://nuxtseo.com/sitemap/guides/multi-sitemaps#managing-sources). 

For example

```ts
sitemap: {
    sitemaps: {
      posts2022: {
        sources: [
          '/api/sitemap-urls?year=2022'
        ]
      },
     posts2023: {
        sources: [
          '/api/sitemap-urls?year=2023'
        ]
      },
    posts2024: {
        sources: [
          '/api/sitemap-urls?year=2024'
        ]
      },
    },
  },
```

There will be improvements in generating this sitemaps list at runtime soon.
