### ISSUE TITLE
当i18n DifferentDomains 为True时生成的站点地图内容不正确

### ISSUE THREAD

**Issue by gaoxu529** [nuxt-modules/sitemap#172]
### Describe the bug

这是当i18n DifferentDomains 为True时生成的站点地图，如下图所示：
![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5687897/affb2fcf-5e68-499c-8dff-e570c6ad8701)
然而，正确的格式应该是这样的：

<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
  <urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
  <changefreq>hourly</changefreq>
  <lastmod>2023-11-20T09:42:24+00:00</lastmod>
  <loc>https://www.footballant.com/</loc>
 <xhtml:link rel="alternate" hreflang="en" href="https://www.footballant.com/" />
  <xhtml:link rel="alternate" hreflang="fr" href="https://fr.footballant.com/" />
   <xhtml:link rel="alternate" hreflang="x-default" href="https://www.footballant.com/" />
   </url>
   <url>
   <changefreq>hourly</changefreq>
   <lastmod>2023-11-20T09:42:24+00:00</lastmod>
   <loc>https://www.footballant.com/about</loc>
   <xhtml:link rel="alternate" hreflang="en" href="https://www.footballant.com/about" />
   <xhtml:link rel="alternate" hreflang="fr" href="https://fr.footballant.com/about" />
   <xhtml:link rel="alternate" hreflang="x-default" href="https://www.footballant.com/about" />
   </url>
</urlset>

**Comment by harlan-zw** [comment]
Please share your i18n config.

**Comment by gaoxu529** [comment]
以下是我的i18n配置示例
i18n: {
    compilation: {
      strictMessage: false 
    },
    baseUrl: process.env.BASE_URL,
    locales: [
      {
        code: 'en',
        name: 'English',
        iso: 'en',
        file: 'en/pc.js',
        domain: www.test.com
      },
      {
        code: 'fr',
        name: 'Français',
        iso: 'fr',
        file: 'fr/pc.js',
        domain: fr.test.com
      },
      {
        code: 'it',
        name: 'Italiano',
        iso: 'it',
        file: 'it/pc.js',
        domain: it.test.com
      },
      {
        code: 'pt',
        name: 'Portuguese',
        iso: 'pt',
        file: 'pt-PT/pc.js',
        domain: pt.test.com
      }
    ],
    differentDomains: true,
    detectBrowserLanguage: false,
    defaultLocale: 'en',
    langDir: 'lang/',
    lazy: true
  },

**Comment by harlan-zw** [comment]
Why are the domains not wrapped in strings? Can you try and provide a StackBlitz reproduction https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue

**Comment by gaoxu529** [comment]
这个是发评论时 漏掉了 引号。

> Why are the domains not wrapped in strings? Can you try and provide a StackBlitz reproduction https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue

**Comment by gaoxu529** [comment]
我在 https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue 中完善了示例代码，生成的站点地图
hr-HR-sitemap.xml和en-US-sitemap.xml从浏览器中看到的是正确的，但是在这个里面我无法使用类似浏览器的查看源码功能查看这两个文件的源文件，我所描述的错误是在这两个文件的源文件中体现的。

**Comment by gaoxu529** [comment]
我找到 hr-HR-sitemap.xml 的源码了，
现在生成的格式如下：
`<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://hr.test.com/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/" />
    </url>
    <url>
        <loc>https://hr.test.com/about/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/about/" />
    </url>
</urlset>
`
正确的格式应该是：
`<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://hr.test.com/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://www.test.com/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/" />
    </url>
    <url>
        <loc>https://hr.test.com/about/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://www.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/about/" />
    </url>
</urlset>
`

**Comment by PabloGBarcelo** [comment]
Hey @gaoxu529, is this happening in the latest version (v5)?
(please, if it's possible answer in english, or use chatgpt, it's easier to track the issue)

**Comment by gaoxu529** [comment]
@PabloGBarcelo 

Yes, this occurred in V5.
My question is: the sitemap content generated when i18n DifferentDomains is set to True is incorrect.

I have improved the example code at https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue.
It can be opened directly in the browser at
https://nuxtstarterj9rgqk-l4mt--3000--9e24d36e.local-corp.webcontainer.io/hr-HR-sitemap.xml, and then you can view the source code by pressing F12.

The format that is currently generated is as follows:
```
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://hr.test.com/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/" />
    </url>
    <url>
        <loc>https://hr.test.com/about/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/about/" />
    </url>
</urlset>
```
But the correct format should be:

```
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://hr.test.com/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://www.test.com/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/" />
    </url>
    <url>
        <loc>https://hr.test.com/about/</loc>
        <xhtml:link rel="alternate" hreflang="hr-HR" href="https://hr.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="en-US" href="https://www.test.com/about/" />
        <xhtml:link rel="alternate" hreflang="x-default" href="https://hr.test.com/about/" />
    </url>
</urlset>
```

**Comment by PabloGBarcelo** [comment]
Something similar was happening on the i18n pages. I’ll take a look as soon as I’m free. Thanks for the example!

**Comment by harlan-zw** [comment]
In 5.3.1 the app sources and `i18n.pages` will respect the domains when generating the alternatives.
