### ISSUE TITLE
Sitemap cache usage with _sitemap-urls.ts?

### ISSUE THREAD

**Issue by notflip** [nuxt-modules/sitemap#194]
### Details

I'm using `_sitemap-urls.ts` to fetch dynamically created pages (using Directus CMS), now I see that the client deleted a page, but the sitemap is not updating, even though I have set the following

```
  modules: [
    [
      "nuxt-simple-sitemap",
      {
        excludeAppSources: ["nuxt:pages"],
        cacheMaxAgeSeconds: 3600,
      },
    ],
}
```

**How do I make sure that updates in the CMS are also reflected in the sitemap?**
Thanks

**Comment by harlan-zw** [comment]
Hi, the sitemap is cached by default for 10 minutes using a SWR caching strategy. You can learn more here: https://nuxtseo.com/sitemap/guides/cache

If you're saying that it's not clearing the cache after 10 minutes, and you're not prerendering it, then it may be a bug I need to look into, can you confirm.

**Comment by notflip** [comment]
@harlan-zw Thanks for getting back, it is not in fact clearing the cache right now, I've made some changes 2 days ago, even did a redeploy on Netlify and I'm still seeing old data. **Is there a method to forcefully clear the cache?**

**Comment by harlan-zw** [comment]
Silly question, but are you sure you're not prerendering the sitemap? Is it possible to share a live URL?

Also please provide the version you're using

**Comment by harlan-zw** [comment]
If you inspect the HTTP response headers it should give you details on the caching. If you provide the live URL i can help with this  (feel free to DM me on discord if you want to keep it private).

To try and debug you can also try disabling the caching by providing `cacheMaxAgeSeconds: 0`

**Comment by notflip** [comment]
@harlan-zw Thanks for helping out, this is the live url: `https://dedirekteurswoning.be/sitemap.xml` The cacheMaxAgeSeconds is now set to 1 hour.

**Comment by harlan-zw** [comment]
Definitely something broken here, current Age is `178400` :thinking: Will try investigate further when I have a chance

**Comment by notflip** [comment]
@harlan-zw Is there a way to forcefully invalidate the cache now? Thanks!

**Comment by PabloGBarcelo** [comment]
Hey @harlan-zw,

I took a look at this, and it seems to be a challenge with Netlify.

Could the problem be related to this topic? [Go to Netlify Forum Post](https://answers.netlify.com/t/netlify-serving-stale-content/55158/6)

> Changing the header breaks the cache invalidation. Cache invalidation only works with the default headers. If you modify the cache-control headers, the new header will modify the caching for any and all URLs that use the modified header.

# My website vs. notflip's website
The request headers are defining the max-age as 0, but the notflip's response is indicating 31536000 (1 year). So maybe we should fix the way the cache control is being injected
![Image](https://github.com/nuxt-modules/sitemap/assets/20051792/e01b65a1-e869-4e97-84b1-2411b1453a96)

**Comment by harlan-zw** [comment]
Going to close this in favour of https://github.com/nuxt-modules/sitemap/issues/288 (duplicate).
