### ISSUE TITLE
Type issue using `index` key on sitemaps

### ISSUE THREAD

**Issue by harlan-zw** [nuxt-modules/sitemap#196]
### Describe the bug

![image](https://github.com/harlan-zw/nuxt-simple-sitemap/assets/5326365/95d762b6-1d57-4743-88a2-7b48415c1057)

> Type '{ pages: { includeAppSources: true; exclude: string[]; }; index: { sitemap: string; }[]; }' is not assignable to type 'boolean | Partial<MultiSitemapEntry & IndexSitemapRemotes> | undefined'.
  Type '{ pages: { includeAppSources: true; exclude: string[]; }; index: { sitemap: string; }[]; }' is not assignable to type 'Partial<MultiSitemapEntry & IndexSitemapRemotes>'.
    Property 'index' is incompatible with index signature.
      Type '{ sitemap: string; }[]' has no properties in common with type 'Partial<SitemapDefinition>'

**Comment by PabloGBarcelo** [comment]
Hey @harlan-zw,

I can't reproduce this behavior. Can you share the nuxt.config?

![image](https://github.com/nuxt-modules/sitemap/assets/20051792/b530d0bc-bcf0-418e-bbbe-452face6c0d1)

**Comment by harlan-zw** [comment]
Thanks for confirming, let's close
