### ISSUE TITLE
@nuxtjs/sitemap version 3 missing

### ISSUE THREAD

**Issue by luminous8** [nuxt-modules/sitemap#205]
Hi,

I'm using @nuxtjs/sitemap@^3.4.1 on my nuxt 2 project

On a clean install I'm getting
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nuxtjs/sitemap@^3.4.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

which doesn't make sense until i check the npm page and discover that none of the v3 version are listed
https://www.npmjs.com/package/@nuxtjs/sitemap?activeTab=versions

How can I fix this issue?

Thanks

**Comment by harlan-zw** [comment]
You need to pin the version to 2.x if you're using Nuxt 2.

Not sure where you got this version from?

**Comment by luminous8** [comment]
your're right, i've updated it in december and didn't have any issue until now 🤔

Thanks for your help!
