### ISSUE TITLE
Lastmod normalise date error

### ISSUE THREAD

**Issue by Henvy-Mango** [nuxt-modules/sitemap#206]
When I use a string like `2023-12-21T22:46:58.441Z`, it is normalized to `2023-12-21T22:46:58`, losing the time zone information. However, when I provide `2023-12-21T22:46:58.441+00:00`, it is converted to the normalized date `2023-12-21T22:46:58+00:00`.

**Comment by harlan-zw** [comment]
Please try 5.0.2 :)
