### ISSUE TITLE
nuxt issue when downloading package

### ISSUE THREAD

**Issue by SantiagoLM01** [nuxt-modules/sitemap#209]
Getting this error when downloading last version of the package: Pre-transform error: Missing "./dist/app/compat/capi" specifier in "nuxt" package

**Comment by PabloGBarcelo** [comment]
Hi @SantiagoLM01 did you read this?
https://github.com/nuxt-modules/sitemap/releases/tag/v5.0.0

Can you provide more information?

**Comment by SantiagoLM01** [comment]
Yes, I read all that and still geting the same error. 

I have a nuxt 3 application with nitro. I wanted to install sitemaps and found your package, but as soon as i install it and run npm run dev i get the errors Pre-transform error: Missing "./dist/app/compat/capi" specifier in "nuxt" package various times.

**Comment by harlan-zw** [comment]
I'd recommend deleting the lock file + node_modules + .nuxt folder and re-installing. It's likely you have an old version of one of the core dependencies that the module is using.

**Comment by creativebob** [comment]
У меня была такая проблема. А произошла она из за того, что в один из компонентов проекта моя IDE автоматически добавила строчку: import { set } from 'nuxt/dist/app/compat/capi'. Я этого не заметил. 

И при npm run dev - вылетала эта ошибка...
