### ISSUE TITLE
Sitemap only shows routes defined in i18n. How can I display all routes?

### ISSUE THREAD

**Issue by DidoMarchet** [nuxt-modules/sitemap#210]
Hi,

When I add some routes to the i18n configuration like this:

```
export default {
  i18n: {
    pages: {
      'policy/privacy': {
        it: '/privacy-policy',
        en: '/privacy-policy',
        'en-us': '/privacy-policy',
      },
      'policy/cookie': {
        it: '/cookie-policy',
        en: '/cookie-policy',
        'en-us': '/cookie-policy',
      },
    },
  },
}
```

The sitemap only shows these routes, not all the pages:
<img width="494" alt="Screenshot 2024-01-10 at 11 43 01" src="https://github.com/nuxt-modules/sitemap/assets/38940340/eb744224-aa41-4bef-a2ca-53fea77c7964">

But if I remove the pages from i18n, it shows all routes:
<img width="648" alt="Screenshot 2024-01-10 at 11 44 21" src="https://github.com/nuxt-modules/sitemap/assets/38940340/e7979043-d8b1-4032-a75d-fd8df9d7c591">

How can I include both types of routes in the sitemap? Should I add all routes in the i18n configuration?

Thanks and best regards,

Davide

**Comment by PabloGBarcelo** [comment]
Hi @DidoMarchet ,

What's the main purpose of doing this?

If you are using custom i18n pages and overriding Nuxt's router, it can be confusing. Are you planning to translate every page, or just those two? This could potentially lead to errors in the future, as using both routers might result in a combination of your i18n pages and the original routes, creating 404 pages.

**Comment by DidoMarchet** [comment]
Hi,
Sometimes, we have routes that don't need translation. 
These routes might be in a specific folder to keep the project tidy, or they could be special dynamic routes that require a unique translation approach. 
This is especially true in large projects (though the example I'm giving is from a smaller project).

But if this is how the module works, we can adjust our configuration to fit.

So the issue can bel close!

Really thanks and kind regards,
Davide
