### ISSUE TITLE
Lastmod date gets converted to wrong date format

### ISSUE THREAD

**Issue by Citingdude** [nuxt-modules/sitemap#214]
In the new 5.0.2 update, the lastmod date gets converted to an invalid date format (see image from Google Search Console). 

The date gets converted to the following format:

`<lastmod>2023-12-11T07:39:59.752706Z</lastmod>`

This should be either: `<lastmod>2023-12-11</lastmod>` OR `<lastmod>2023-12-11T18:00:15+00:00</lastmod>` to be valid according to google. 

See https://developers.google.com/search/blog/2006/04/using-lastmod-attribute for reference.

![image](https://github.com/nuxt-modules/sitemap/assets/80922251/143b84e4-c771-40f5-9be8-f18c309edd63)

**Comment by PabloGBarcelo** [comment]
@harlan-zw 2023-12-11T07:39:59.752706Z complains to the W3C but not to Google. Would it be better to adhere to Google's format or add another property to the Nuxt config indicating whether it should complain to Google?

**Comment by Citingdude** [comment]
I think I have actually misread the W3C document, the current format should be valid according to W3C and also google. 

The issue with previous dates was the absence of the timezone.
( `2023-12-11T07:39:59.752706Z`)

Following examples should be valid dates:

- 1997
- 1997-07
- 1997-07-16
- 1997-07-16T19:20+01:00
- 1997-07-16T19:20:30+01:00
- 1997-07-16T19:20:30.45+01:00

But also:
- 1997-07-16T19:20Z
- 1997-07-16T19:20:30Z
- 1997-07-16T19:20:30.45Z

**Comment by harlan-zw** [comment]
I feel like the issue is related to the milliseconds being included, currently investigating futher.

**Comment by harlan-zw** [comment]
Please try 5.0.3 :pray: Also can you please provide some reproduction on how the lastmod is being set.
