### ISSUE TITLE
Type '[string, { headers: { accept: string; }; }]' is not assignable to type 'SitemapSourceInput'. ts(2322)

### ISSUE THREAD

**Issue by lxccc812** [nuxt-modules/sitemap#215]
According to the [documentation](https://nuxtseo.com/sitemap/guides/dynamic-urls#_1-using-sources-config), I get this error when I want to configure request headers for my source.

![image](https://github.com/nuxt-modules/sitemap/assets/110974969/7f3abf43-ddb3-451b-b618-b0e71cf6fe4c)

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.13.1
- Builder:          -
- User Config:      modules, ssr, runtimeConfig, app, css, devServer, devtools, device, experimental, gtm, nitro, pwa, sitemap
- Runtime Modules:  nuxt-swiper@1.2.2, @unocss/nuxt@0.57.7, @vueuse/nuxt@10.7.1, @nuxtjs/device@3.1.1, @vite-pwa/nuxt@0.1.2, @nuxtjs/sitemap@5.0.3, @zadigetvoltaire/nuxt-gtm@0.0.13
- Build Modules:    -
------------------------------

**Comment by harlan-zw** [comment]
Thanks, should be fixed in 5.0.4
