### ISSUE TITLE
i18n pages + external sitemap

### ISSUE THREAD

**Issue by razorness** [nuxt-modules/sitemap#216]
Hey, I am trying to add an external sitemap from strapi to my i18n Pages routing.

```ts
  sitemap      : {
    sitemaps: {
      index: [
        {
            sitemap: 'https://domain.com/cms/api/sitemap/index.xml'
        }
      ]
    }
  },
```

Anyhow, I don't get it working. It looks like support for i18n pages is only applied if I don't touch `sitemaps` settings at all:

https://github.com/nuxt-modules/sitemap/blob/d882b8e7a9d96da50c6343aaa75b868a2ff386d8/src/module.ts#L207-L216

Is there any possible configuration to use the automatic support of i18n Pages with a reference to an external sitemap?

**Comment by harlan-zw** [comment]
Thanks for the isuse, this is fixed in 5.0.5
