### ISSUE TITLE
Trailing slashes getting removed by @nuxtjs/sitemap

### ISSUE THREAD

**Issue by hankdetank** [nuxt-modules/sitemap#219]
Dear all,

Nuxt version: 3.9.3
@Nuxtjs/sitemap version: 5.0.5

My config is as follows:

> sitemap: {
>     urls: async () => {
>       return [{
>         loc: '/blog/abc/',
>         changefreq: 'weekly',
>         priority: 0.7
>       }]
>     },  
>     sitemaps: {
>       posts: {
>         includeAppSources: true,
>         include: [
>           '/blog/**'
>         ],
>         defaults: { priority: 0.8 },
>       },
>     }
> }

The result becomes:
`http://localhost:3000/blog/abc`

The expected result is:
`http://localhost:3000/blog/abc/`

What is the reason the Trailing slash gets removed by @nuxjs/sitemap?

**Comment by harlan-zw** [comment]
Please see https://nuxtseo.com/nuxt-seo/guides/trailing-slashes.

I'll keep this open until the sitemap module has a dedicated docs page for it too
