### ISSUE TITLE
Sitemaps typing problem

### ISSUE THREAD

**Issue by dapzer** [nuxt-modules/sitemap#222]
When placing a valid object as a value for the `sitemaps` field, it generates typing errors.
![image](https://github.com/nuxt-modules/sitemap/assets/78279257/4b2c51b9-98d7-4f44-a498-15fe9756c810)

Code:

```
  sitemap: {
    cacheMaxAgeSeconds: 24 * 60 * 60,
    defaultSitemapsChunkSize: 2000,
    sitemaps: {
      index: [
        { sitemap: `${process.env.VITE_API_URL}/sitemaps/sitemap-index.xml.gz` }
      ]
    }
  },
```

**Comment by harlan-zw** [comment]
Hi, in v5.1.0 I've introduced a new config `appendSitemaps` that does the same thing that won't have these type issues.

Your config seems a little strange, guessing you have omited some of it? You should change your config to:

```ts
 sitemap: {
    // ...
	appendSitemaps: [`${process.env.VITE_API_URL}/sitemaps/sitemap-index.xml.gz`]
  },
```

**Comment by dapzer** [comment]
No, this is the entire configuration associated with the sitemap module  ([source](https://github.com/dapzer/movie-tracker/blob/master/apps/frontendVue/nuxt.config.ts#L33)). Thanks for the solution, I will try it later!
