### ISSUE TITLE
unable to exclude URL from sitemap 

### ISSUE THREAD

**Issue by azuryel** [nuxt-modules/sitemap#224]
Hello, i'm not sure why but im unable to ignore any URL in my sitemap. i'm trying to hide the admin panel from it. 
Here is my nuxt.config.ts: 

```
 sitemap: {
      exclude: ["/fr/admin/**', '/en/admin/**', '/admin/**"],
      debug: true,
      cacheMaxAgeSeconds: 10,
      defaultSitemapsChunkSize: 10,
      sitemaps: {
        pages: {
          includeAppSources: true,
          exclude: ["/fr/admin/**', '/en/admin/**', '/admin/**"],
        },
      },
      routeRules: {
        "/admin": {
          index: false,
          robots: false,
        },
        "/en/admin/**": { robots: false, index: false },
        "/fr/admin/**": { robots: false, index: false },
      },
```

and here is my sitemap results

![image](https://github.com/nuxt-modules/sitemap/assets/9035821/70cc933a-a6b8-49fd-997e-154894846a44)

**Comment by harlan-zw** [comment]
Would you mind also providing your i18n config so I can replicate it fully? A stackblitz reproduction would also speed this issue along.

**Comment by azuryel** [comment]
my i18n config in nuxt.config.ts

```
 i18n: {
    defaultLocale: "en",
    locales: [
      {
        code: "en",
        iso: "en-US",
        file: "en.json",
        name: "English",
      },
      {
        code: "fr",
        iso: "fr-FR",
        file: "fr.json",
        name: "Francais",
      },
    ],
    langDir: "locales/",
  },
```

unfortunately i wont be able to do a stackblitz for reproduction on it as i dont have access to my main computer right now and for some time still

**Comment by harlan-zw** [comment]
Thanks, will try take a look in the next couple of days :)

**Comment by harlan-zw** [comment]
I've tried to replicate using the latest version and your config without any issues. I'll need a reproduction to investigate further.
