### ISSUE TITLE
defineSitemapEventHandler is not defined   

### ISSUE THREAD

**Issue by liaow-ww** [nuxt-modules/sitemap#228]
![image](https://github.com/nuxt-modules/sitemap/assets/115768717/2db44a8b-7ea2-484f-84b2-32d0b09a6b33)
![image](https://github.com/nuxt-modules/sitemap/assets/115768717/4abe3189-88ee-4c07-97cf-a4f374678478)
![image](https://github.com/nuxt-modules/sitemap/assets/115768717/1233ec46-8c21-4ca2-beef-d6b00a0e5451)

I can't use defineSitemapEventHandler

**Comment by harlan-zw** [comment]
You need to make sure you have a `tsconfig.json` in your `server` directory that has

```json
{
  "extends": "../.nuxt/tsconfig.server.json"
}
```

Or pointed at wherever the folder is.
