### ISSUE TITLE
Export more types

### ISSUE THREAD

**Issue by rudolfbyker** [nuxt-modules/sitemap#234]
I wish to do something like this:

```
import type { SitemapUrlInput } from "@nuxtjs/sitemap/dist/runtime/types";

export default defineCachedEventHandler(getSitemapEntries, {
  // ...
});

async function getSitemapEntries(): Promise<SitemapUrlInput[]> {
  // ...
}
```

But on the `import` line, I get `TS2307: Cannot find module @nuxtjs/sitemap/dist/runtime/types or its corresponding type declarations.`. It seems that I can only import types from `@nuxtjs/sitemap` directly, which does not export the types I need.

Would it be possible to export more types?

**Comment by rudolfbyker** [comment]
Workaround for now:
```ts
import type { SitemapUrlInput } from "~/node_modules/@nuxtjs/sitemap/dist/runtime/types";
```

**Comment by nandi95** [comment]
Another workaround:
```ts
type SitemapEntryInput = Exclude<Exclude<ModuleOptions['urls'], Promise<any> | CallableFunction | undefined>[number], string>;
```

**Comment by harlan-zw** [comment]
Good idea, I've introduced an alias `#sitemap` which points to the runtime types.

You should be able to do this in 5.1.1.

```ts
import type { SitemapUrlInput } from "#sitemap";
```
