### ISSUE TITLE
Localized Sitemap Chunking Issue with i18n Integration

### ISSUE THREAD

**Issue by V1laZ** [nuxt-modules/sitemap#236]
### Describe the bug
When generating the sitemap with the i18n module and fetched dynamic URLs, it divides the sitemap into locale chunks. However, it fails to automatically further divide these chunks when they are too large, even with the `sitemaps: true` setting enabled.

### To reproduce
1. **package.json** with the following dependencies
```json
    "@nuxtjs/i18n": "^8.0.0",
    "@nuxtjs/sitemap": "^5.1.0",
```
2. **nuxt.config.ts** with the following settings
```js
  i18n: {
    vueI18n: './i18n.config.ts',
    defaultLocale: 'cs',
    strategy: 'prefix',
    langDir: 'locales/',
    lazy: true,
    locales: [
      {
        code: 'cs',
        iso: 'cs-CZ',
        name: 'Čeština',
        file: 'cs.json',
      },
      {
        code: 'en-us',
        iso: 'en-US',
        name: 'English (US)',
        file: 'en_us.json',
      },
      ...
    ]
  },

  sitemap: {
   sitemaps: true,
   sources: [
     `${process.env.BACKEND_URL}/api/services/sitemap/`,  // sends JSON with relative paths without locales
   ]
  },
```
3. Open _/sitemap.xml_
4. The sitemap is chunked by locales, but within each locale chunk, there are, for example, 13000 URLs even with `sitemaps: true`.
[Locale chunks](https://i.imgur.com/KJZqx2Z.png)
[Inside the locale chunk](https://i.imgur.com/cg77lv1.png)

### Expected behavior
Either locale chunks should contain multiple chunked sitemap files if they are too large, or the sitemap should be chunked as a whole by the specified chunk size with locale paths. 

### Notes
I'm not sure if this is a problem with my settings, but I've tried multiple combinations and none worked. It either doesn't generate localized URLs, even when making my own endpoint and specifying `_i18nTransform: true` to every URL, or it chunks them by locales as described above.

**Comment by harlan-zw** [comment]
This is not currently supported. 13k URLs should not be an issue for Google.

**Comment by gianLuigiL** [comment]
I have the same issue with 94k urls

**Comment by gianLuigiL** [comment]
I'm curious if there's a way to detach form localizing the sitemap as at least it would not be grouped but i can construct the urls myself and have the plugin just chunk the result

**Comment by danekslama** [comment]
This is probably a slightly better solution, which will include all the locales in the sitemaps. The alternatives field acts as a metadata field only.

```ts
interface SitemapUrl {
  loc: string
  lastmod: string
}

const locales = ['cs', 'sk', 'en', 'es', 'es-419', 'de', 'fr', 'pl', 'it', 'sl']

export default defineSitemapEventHandler(async () => {
  const config = useRuntimeConfig()
  const response = await $fetch<SitemapUrl[]>(
    `${config.public.backendUrl}/api/services/sitemap/`,
    {
      timeout: 10000,
    },
  )

  return response.flatMap(p =>
    locales.map(locale =>
      asSitemapUrl({
        loc: `/${locale}${p.loc}`,
        lastmod: p.lastmod,
        alternatives: locales.map(l => ({
          hreflang: l,
          href: `/${l}${p.loc}`,
        })),
      }),
    ),
  )
})

```
