### ISSUE TITLE
i18n & @nuxt/sitemap with dynamic routes is not working.

### ISSUE THREAD

**Issue by IvanWala** [nuxt-modules/sitemap#240]
Hi need to create a conector for a big site with more than 10000 routes many dinamic. It is prepared in the backend for serve the active routes. Our problem is when you convine i18n and Nuxt/sitemap. I 18n is blocking the routes. I make astackblitz the convination of

[Dynamic Routes](https://stackblitz.com/edit/nuxt-starter-dyraxc?file=server%2Fapi%2F_sitemap-urls.ts)
[i18n](https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue)

I doesn't seems to work. i18n is making it's own sitemap wrapper and every locale xml doesn't exist (link "broken").

https://stackblitz.com/edit/nuxt-starter-dc1h21?file=server%2Fapi%2Fsitemap.ts

When this is solved we need to serve the routes from the backend.

**Comment by BghinC** [comment]
Hey, I faced this error too. What I did is:

- Define the sources property and set the urls of your apis.
```
// nuxt.config.ts
sitemap: {
  sources: ['/api/sitemap/my-dynamic-urls'],
},
```

- On your api endpoint, you should return your dynamic urls in a specific format:
```
export default defineSitemapEventHandler(() => {
  return [
    {
      loc: '/about-us',
    },
  ]
})
```

Using i18n you have one sitemap per language. Here the `/about-us` url will be added to the sitemap of your default language. If you want to add, let's say, a `/company` page on your french sitemap you'll have to define it like that:

```
export default defineSitemapEventHandler(() => {
  return [
    {
      loc: '/about-us',
    },
    {
      loc: '/company',
      _sitemap: 'fr-FR',
    },
  ]
})
```

Using this method you should be able to combine @nuxt/i18n with @nuxt/sitemap

**Comment by harlan-zw** [comment]
Not sure I understand the issue, the reproduction looks like it's working correctly. Note that in StackBlitz you'll need to directly visit the child sitemap path (you can't click the link).

Also please see the [i18n integration docs](https://www.nuxtseo.com/sitemap/integrations/i18n).

**Comment by IvanWala** [comment]
Thanks i created my own sitemap without the plugin. The i18n sitemaps doesn't exist (The link is broken) or the documentation doesn't explain how to create them.
