### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by AncaEmilia** [nuxt-modules/sitemap#241]
I use the nuxt-simple-sitemap module and in production when I access /sitemap.xml I get 301 Moved Permanently response and I am redirect to homapage. 
After I updated to nuxtjs/sitemap, I have the same problem, I can't even view the local sitemap/xml.

nuxt.config.ts: 
 ```
 site: {
		url: process.env.NUXT_BASE_URL,
 },
  sitemap: {
    sitemaps: {
      pages: {
        includeAppSources: true,
        sources: ['/api/_sitemap-pages'],
        exclude: [
          '/'
        ],
      },
      index: [
        { sitemap: 'https://*******.ro/blog/wp-sitemap-posts-post-1.xml' }
      ]
    }
  },
```

api/_sitemap-pages:
 ```
export default defineEventHandler(
  async (e) => {
    return [
      {
        loc: '/about-us',
        // will end up in the pages sitemap
        _sitemap: 'pages',
      }
    ]
    
  }
);
```

I use defineEventHandler because I have error on defineSitemapEventHandler even i set "extends": "./.nuxt/tsconfig.json" in tsconfig.json.

**Comment by harlan-zw** [comment]
Hi, you shouldn't be directed to the home page, you should be directed to `/sitemap_index.xml` because you're using a multi-sitemap.

If you visit the path `/sitemap_index.xml` in the browser you should see your sitemap.

**Comment by AncaEmilia** [comment]
Hi, even I made a a separate tsconfig.json in my server folder, I have the same issue: 
`Error: [unimport] failed to find "defineSitemapEventHandler" imported from "#imports"`
And event for /sitemap_index.xml, I receive 200 status on network, and I am redirect to homepage ..

**Comment by AncaEmilia** [comment]
and if I try to validate my sitemap_index.xml, on: https://www.xml-sitemaps.com/validate-xml-sitemap.html,  I have this error: 
`Incorrect http header content-type: "text/html" (expected: "application/xml")`

**Comment by harlan-zw** [comment]
It sounds like a server issue? Can you provide a reproduction
