### ISSUE TITLE
Dynamic Url does not generate url path which includes query param

### ISSUE THREAD

**Issue by longhuubaotran** [nuxt-modules/sitemap#242]
**### Describe the bug**
I have dynamic endpoints that return `{loc: '/about-us?search=abc', _i18nTransform: true}`, the sitemap will be `/about-us`, the part `?search=abc` got removed, but If I remove the line `_i18nTransform: true`, I get the correct sitemap `/about-us?search=abc`

**### To reproduce**
https://stackblitz.com/edit/nuxt-starter-owzetq?file=server%2Fapi%2Fsitemap.ts

package.json in my machine
`    "@nuxtjs/i18n": "^8.0.0-rc.4",
    "@nuxtjs/sitemap": "^5.1.1",
`

I have my dynamic url endpoint like this, I enable ` _i18nTransform: true`
<img width="744" alt="Screen Shot 2024-03-07 at 9 48 50 PM" src="https://github.com/nuxt-modules/sitemap/assets/48188258/310a5e23-be46-4c0b-9dba-77dc3afbb668">

And this is result, the part `?search=abc` which got removed
<img width="871" alt="Screen Shot 2024-03-07 at 9 50 07 PM" src="https://github.com/nuxt-modules/sitemap/assets/48188258/a46908db-a136-484b-8760-b6d4defeb1b6">

If I remove the ` _i18nTransform: true` option, it works normally
<img width="837" alt="Screen Shot 2024-03-07 at 9 51 50 PM" src="https://github.com/nuxt-modules/sitemap/assets/48188258/a17269f6-feed-4529-a115-c5ea2185f276">

**Comment by longhuubaotran** [comment]
In my opinion, in the source code, it should be like this (`sitemap.ts` &` i18n.ts`)
<img width="875" alt="Screen Shot 2024-03-08 at 12 44 33 AM" src="https://github.com/nuxt-modules/sitemap/assets/48188258/32ae02fe-8783-4921-8c0a-9aac33e5d01b">
<img width="1076" alt="Screen Shot 2024-03-08 at 12 44 44 AM" src="https://github.com/nuxt-modules/sitemap/assets/48188258/374cf350-c489-45c0-a5dc-16cac945fb72">

I tried to create a new PR but I don't have permission

**Comment by harlan-zw** [comment]
Hey, thanks for the issue and investigation. Happy to take a look at this but may be quicker for you to land a PR.

To do so you need to fork the repository, clone it locally and then push up changes to your forked repo. Then you'll be given a prompt to make a PR against this repo.

**Comment by longhuubaotran** [comment]
Thanks for helping me in making PR, could you please check my fix ?
