### ISSUE TITLE
How to disable i18n localization?

### ISSUE THREAD

**Issue by gianLuigiL** [nuxt-modules/sitemap#244]
Referring to [https://github.com/nuxt-modules/sitemap/issues/236](url) i understand automatic chunking for localized sitemaps is not supported. Can i manually create the urls for every locale but i don't understand how to disable i18n integration and manually create all urls myself.

I've added `autoI18n: false` but then i get a sitemap with no content, screen below:
![image](https://github.com/nuxt-modules/sitemap/assets/41172153/e85e67ed-6a67-409a-ae89-dd5d32eeb121)

Here's my config:
```
  sitemap: {
    sitemaps: true,
    exclude: [
      "/adds/**",
      "/admin/**",
      "/email-expired",
      "/email-verified",
      "/favourites",
      "/profile",
      "/request-new-password",
      "/reset-password",
      "/verify-email",
    ],
    sources: ["/api/__sitemap__/urls"],
    // 24 hours
    cacheMaxAgeSeconds: 3600 * 24,
  }
```

**Comment by gianLuigiL** [comment]
Hello Harlan sorry my post above is a bit unclear.
I've attached a screenshot with the results of adding `autoi18n: false` then it bugs out and tells me I have 0 urls in my index. Don't know what to do to work around that.
![image](https://github.com/nuxt-modules/sitemap/assets/41172153/db52fc51-614d-4917-8fa1-4d3a6bcda4e1)

**Comment by harlan-zw** [comment]
Hm possibly combine with `sitemaps: true`?

I'll investigate further soon

**Comment by gianLuigiL** [comment]
Thanks Harlan I've updated the post above with my config and i'll add it here too:
```
  sitemap: {
    sitemaps: true,
    exclude: [
      "/adds/**",
      "/admin/**",
      "/email-expired",
      "/email-verified",
      "/favourites",
      "/profile",
      "/request-new-password",
      "/reset-password",
      "/verify-email",
    ],
    sources: ["/api/__sitemap__/urls"],
    // 24 hours
    cacheMaxAgeSeconds: 3600 * 24,
  }
```
Please note in this config I'm not using `autoi18n: false` because otherwise it would not render at all.

Thank you very much for your work 🙏

**Comment by harlan-zw** [comment]
I'm going to close this as I think it's stale and the reproduction isn't clear.

If you're still having issues please make a [reproduction](https://stackblitz.com/edit/nuxt-starter-jwuie4?file=app.vue) and I'll take a further look.
