### ISSUE TITLE
lastmod does not render

### ISSUE THREAD

**Issue by henrikhansson** [nuxt-modules/sitemap#246]
I'm having the issue that the `lastmod` element does not render for any pages when running `npm run generate`. Is this expected behavior for generated sites? This is not isolated to one app, just made a minimal install with two pages, sitemap renders as expected but without `lastmod` element.

sitemap.xml

```
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="/__sitemap__/style.xsl"?>
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>http://localhost:3000</loc>
    </url>
    <url>
        <loc>http://localhost:3000/other</loc>
    </url>
</urlset>
<!-- XML Sitemap generated by @nuxtjs/sitemap v5.1.2 at 2024-03-12T14:16:20.021Z -->

```

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  site: {
    url: "http://localhost:3000/"
  },
  modules: ["@nuxtjs/sitemap"],
});

```

**Comment by harlan-zw** [comment]
Are you setting a `lastmod`? Automatically lastmods based on deploys were disabled as they are against Google's guidelines. See https://nuxtseo.com/sitemap/guides/best-practices#set-appropriate-lastmod

**Comment by henrikhansson** [comment]
Sorry, I completely missed this part of the documentation. Thank you!

**Comment by harlan-zw** [comment]
I'm not too sure, possibly you could use the last time the file was updated within git, you can't rely on the fs updated at times.

If you find a solution, let me know. Would be good to post a recipe on the docs for this.

**Comment by henrikhansson** [comment]
I'm mostly working with Storyblok based projects and using `published_at` for each story would be a good candidate. That in combination with `defineRouteRules` should make it possible to add a correct `lastmod` to each page something like this:

```js
defineRouteRules({
  sitemap: {
    lastmod: story.published_at,
  }
})
```

However, working with catch all pages will probably make things a bit more complicated, will report back when I have a solution.

**Comment by harlan-zw** [comment]
If you're using Storyblok you should use a [dynamic URL endpoint](https://nuxtseo.com/sitemap/guides/dynamic-urls) and you can provide the lastmod's with it?
