### ISSUE TITLE
Nuxt content paths are still added when setting documentDriven false

### ISSUE THREAD

**Issue by JarvisChao** [nuxt-modules/sitemap#247]
```typescript
modules: [
  '@nuxt/content',
  '@pinia/nuxt',
  'nuxt-simple-robots',
  '@nuxtjs/sitemap'
],
content: {
  documentDriven: false
},
robots: {
  disallow: appBaseUrl === '/testing' ? '/' : ''
},
sitemap: {
  sources: [
    '/api/__sitemap__/urls'
  ]
}
```

![截圖 2024-03-14 01 28 50](https://github.com/nuxt-modules/sitemap/assets/38325453/07160fca-f6b0-447d-999b-2d390d9c0c39)

![截圖 2024-03-14 01 42 41](https://github.com/nuxt-modules/sitemap/assets/38325453/2311fa98-361f-4b64-b0f5-61cc93c58136)

![截圖 2024-03-14 01 41 50](https://github.com/nuxt-modules/sitemap/assets/38325453/1a057b15-6bc0-4b3f-8f18-c9e31349e8ee)

**Comment by JarvisChao** [comment]
Solved this problem by adding the "_" inside the content folder
```
content/
  _product/
  _news/
```

**Comment by harlan-zw** [comment]
The Nuxt Content integration works without `documentDriven` if you have specified the `path` within a markdown file.

If your intention is to not have these indexable, I'd suggest using a `_dir.yml` file and setting `index: false` or `sitemap: false`.
