### ISSUE TITLE
Create sitemap index at runtime

### ISSUE THREAD

**Issue by niklas-may** [nuxt-modules/sitemap#249]
First of all: Thanks for this great module!!

I have a site with a dynamic route generating pages from an external API, currently totaling 20K pages and expanding. To build the sitemap for this route, I plan to use a server route with `defineSitemapEventHandler` (which works great!). However, in my case, creating a single sitemap takes too long and is not an option. Therfore I am looking to find a way to create multiple sitemaps for this route. If i understand the docs correctly, the only method to achieve this is to manually add properties to the sitemap config like this:

```JavaScript
// nuxt.config.ts
 { 
  sitemaps: {
    "posts-01-2023": {
      sources: ['/api/__sitemap__/urls?month=1&year=2024']
    },
    "posts-02-2024": {
      sources: ['/api/__sitemap__/urls?month=2&year=2024']
    }
  }
}
```

Is there a way to create / extend the sitemap index programmatically a runtime? Did I miss something in the docs? 

If not, I think it would be great if there was a way to do so. Something like this:

```JavaScript
export default defineEventHandler(async () => {
  /* Fetch my api with dynamic routes */
  const res = await fetchMyApi();
  /* Have some custom function that determines how 
   * many sitemaps are needed, how to name them, 
   * how to create them. */ 
  const chunks = myCustomFunction(res);
  return chunks.map((chunk) => {
  /* Call a new function that returns sitemap index entries */
    return asSitemapIndex({
      // e.g posts-01-2024
      name: chunk.name,
      // e.g. '/api/__sitemap__/urls?month=1&year=2024'
      source: chunk.source,
    });
  });
});
```

And then add this endpoint to the config:

```JavaScript
{
  sitemap: {
    sitemaps: {
      index: [{ source: "/api/__sitemap__/index" }],
    }
  }
}
```

Do you see this as a relevant feature to put on the roadmap? If so, I am more than happy to create a PR.

**Comment by harlan-zw** [comment]
This may be a bit complicated but the feature does make sense and seems useful for larger sitemaps. It partially solves the automatic chunking for multi-sitemaps that have been requested a number of times.

A current workaround is just programmatically creating the sitemaps at build-time, depending on your API you would use a `since` query to fetch all records since the last deployment in its own sitemap.

**Comment by harlan-zw** [comment]
This should be possible using https://nuxtseo.com/sitemap/nitro-api/nitro-hooks#sitemapindex-resolved
