### ISSUE TITLE
Problem with i18n integration

### ISSUE THREAD

**Issue by mrc-bsllt** [nuxt-modules/sitemap#252]
By integrating with i18n, it correctly creates me separate files according to the locales, but the dynamic routes are merged between the files (in the sitemap en I also find the dynamic routes of hr, and vice versa). IncludeAppSources: true does not work in this reproduction either, but I think it is due to the installed version, because in my project that works.

stackblitz: https://stackblitz.com/edit/nuxt-starter-cv5hf9?file=nuxt.config.ts

![Screenshot 2024-03-22 alle 09 27 12](https://github.com/nuxt-modules/sitemap/assets/72490444/f7764659-2420-4cd8-aa7a-c763073cbbd0)

**Comment by harlan-zw** [comment]
Hey, please see the docs here on how to resolve this: https://nuxtseo.com/sitemap/integrations/i18n#dynamic-urls-with-i18n
