### ISSUE TITLE
Would it be possible to have a sitemap filter by layout type?

### ISSUE THREAD

**Issue by acidjazz** [nuxt-modules/sitemap#253]
All of our public pages use a layout of `public` while our gated pages that we do not want mapped use a layout of `default`.  Is this possible?

**Comment by harlan-zw** [comment]
Hey, this seems like a reasonable suggestion.

I'm not too sure what the config / API would look like around this and I think the page meta availability within the module may have some constraints.

I would encourage you to explicitly mark these layouts as non-indexable though. This module integrates with Nuxt Simple Robots which lets you disable indexing of groups of pages using [route rules](https://nuxtseo.com/robots/guides/route-rules).

Does this work or would a Page Meta config work?

**Comment by harlan-zw** [comment]
I don't think this will get implemented so going to close. The best option for any bespoke automation would be setting up your own [Nitro hooks](https://nuxtseo.com/sitemap/nitro-api/nitro-hooks).
