### ISSUE TITLE
Sitemap not compatible with definePageMeta().path

### ISSUE THREAD

**Issue by jeannen** [nuxt-modules/sitemap#255]
Hey!

It seems like there is an issue when using the sitemap in combination with the `path` property of definePageMeta.

Instead of using the proper path, the sitemap is generated using the `/pages` files, even if they have a custom path.

For example, if I have `/app/note-list.vue` with a custom path to use it as the index of a folder (better for organization purposes):

```JS
    definePageMeta({
        path: '/app/',
    });
```

I will get the following error when generating the website while doing `npm run generate`. I think it might be because the generation switch to using the sitemap instead?

```
  ├─ /app/note-list (886ms)                                                                                                                                                             nitro 9:11:44 AM
  │ └── Error: [404] Page not found: /app/note-list
```

The issue seems to persists even when I exclude every page in `nuxt.config.ts`

```
 sitemap: {
        exclude: ['**'],
    },
```

I use NuxtSEO directly, so it might be another module maybe? As soon as I remove NuxtSEO it the issue is gone

**Comment by harlan-zw** [comment]
This appears to be a Nuxt bug, see the reproduction: https://stackblitz.com/edit/nuxt-starter-k6cb5d?file=pages%2Fapp%2Fnote-list.vue.

I'm not too sure what the solution is meant to look like but I'd encourage you to open an issue on https://github.com/nuxt/nuxt/issues with this reproduction if it's something you want to solve.
