### ISSUE TITLE
Pages are logged in the console when running yarn dev or yarn build

### ISSUE THREAD

**Issue by Bakusedu** [nuxt-modules/sitemap#261]
Thanks @harlan-zw for all of your efforts in ensuring this plugin is stable. I actually noticed a little issue after using the latest release of the plugin. All pages in my application are being logged out when running `yarn dev` or `yarn build`

I actually traced the issue to this file:
<img width="1604" alt="Screenshot 2024-04-08 at 19 26 01" src="https://github.com/nuxt-modules/sitemap/assets/34550806/051ca97b-bb50-4039-a993-cc9b68c46e88">
Nothing seems broken at the moment as a result of this, just thought i should raise it as a concern. Thanks

**Comment by harlan-zw** [comment]
🤦 Looks like some debug artifacts got in the build, I've pushed up v5.1.4 that removes this.
