### ISSUE TITLE
Inability to exclude specific routes while including others

### ISSUE THREAD

**Issue by DouglasAR01** [nuxt-modules/sitemap#263]
Hi. Is it possible to create a combination of include and exclude for specific scenarios? Let's say I would like to exclude all routes inside `/col` except for `/col/test`. 
I tried with
`exclude: ['/col/**'],
include: ['/col/test']`

But that, apparently, doesn't work.

**Comment by harlan-zw** [comment]
Unfortunately, this isn't possible without a major breaking change as the filter checks for exclude rules first with a return early strategy

In later versions of the module, we have added full regex support so that may give you the functionality you require.
