### ISSUE TITLE
Generate sitemap with CLI

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/sitemap#266]
Currently it seems like `/sitemap.xml` is a dynamic route that the Nuxt server resolves rather than an actual file. This might be fine for most use cases but for example on Vercel this will resolve to a 404 page, issue: https://github.com/nuxt-modules/sitemap/issues/256

It would be nice if the sitemap can be generated as a file in the build step by CLI, e.g. `nuxt build && nuxt-sitemap generate`. This would fix the issue above.

**Comment by harlan-zw** [comment]
Hi, sorry for the delay.

I'm not exactly sure what is going on with Vercel Edge that it doesn't work, but you should just be able to add the sitemap path to the pretender routes and it will generate it statically.

```ts
export default defineNuxtConfig({
  nitro: {
    prerender: {
      routes: ['/sitemap.xml']
    }
  }
})
```

I'm happy to enable the static generation by default on Vercel if you can make a minimal reproduction.
