### ISSUE TITLE
Type issue when importing module

### ISSUE THREAD

**Issue by ps-20x** [nuxt-modules/sitemap#274]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.20.2`
- Nuxt Version:     `3.11.2`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.6`
- Package Manager:  `npm@10.5.0`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

1. Checkout https://github.com/ps-20x/phpstorm-issues
2. Run `npm ci`
3. Open utils/createSitemapItem.ts
4. Import type shows an error

### Describe the bug

The following error is showing up:

>`Vue: Cannot find module @nuxtjs/sitemap/dist/runtime/types or its corresponding type declarations.`

### Additional context

Tried it in PHPStorm as well as in VSCode. The project is an almost plain project.

PHPStorm
![image](https://github.com/nuxt/nuxt/assets/126659880/2042b114-9e37-445e-80e9-8b5f30cf8a4e)

VSCode
![image](https://github.com/nuxt/nuxt/assets/126659880/bf931bb4-5718-4930-a833-ea9da85d8b38)

You can check out more information on the type issues here: https://arethetypeswrong.github.io/?p=@nuxtjs/sitemap@5.1.4 (thanks to @danielroe)

This issue was initially raised in the nuxt repository: https://github.com/nuxt/nuxt/issues/26955

**Comment by harlan-zw** [comment]
Please follow the docs and use the util function to extract the types, see https://nuxtseo.com/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint

Type support via dist runtime is not supported from the nuxt-module-builder currently afaik. There is work around for this but the sitemap module has not implemented them

**Comment by ps-20x** [comment]
> Please follow the docs and use the util function to extract the types, see https://nuxtseo.com/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint

Thanks for your suggestion and help.

This worked for my `SitemapUrl`. But I can't figure out on how to get types for the values in there.

```ts
// works
type SitemapUrl = ReturnType<typeof asSitemapUrl>;
// does not work
type Priority = SitemapUrl["priority"];
type Changefreq = SitemapUrl['changefreq'];
```
I am getting the message:
> Property `priority` does not exist on type `SitemapUrlInput`

**Comment by ps-20x** [comment]
> I've pushed up some improvements in [v5.1.5](https://github.com/nuxt-modules/sitemap/releases/tag/v5.1.5) for the types.
> 
> An alias is now added that points to the runtime types directly, it's at `#sitemap`.
> 
> ```ts
> import type { SitemapUrl } from '#sitemap'
> ```
> 
> Let me know if you have any issues.

Worked perfectly thank you 🙇
