### ISSUE TITLE
Headers are not sent when set from sources

### ISSUE THREAD

**Issue by enshaded** [nuxt-modules/sitemap#275]
**nuxt**: 3.11.2
**@nuxtjs/sitemap**: 5.1.4

```ts
export default defineNuxtConfig({
  sitemap: {
    sources: [
      // hit a remote API with credentials
      ['/__sitemap__/urls', { headers: { Authorization: 'Bearer <token>' } }]
    ]
  }
})
```

When I check headers on the server ```Authorization``` header is missing.
```
{ accept: 'application/json', host: 'localhost' }
```

**Comment by adamdehaven** [comment]
@harlan-zw any way to provide these headers at runtime?

**Comment by harlan-zw** [comment]
Not currently @adamdehaven  I can make a Nitro hook to do so easily enough. If you make a new issue with your requirements I'll implement and test it'll work for you

**Comment by adamdehaven** [comment]
@harlan-zw let me know if you need more info:
https://github.com/nuxt-modules/sitemap/issues/433
