### ISSUE TITLE
Sitemap generation is drastically slower after version `5.1.5`

### ISSUE THREAD

**Issue by F0rsaken** [nuxt-modules/sitemap#282]
Hi!

I have a specific case, where I need to generate A LOT of sitemaps with different languages. Untill version `v5.1.4`, single sitemap generated in approximately 2s. Since `v5.1.5` it taks 5-6x longer. In `v5.2.0` it was reduced to ~4x times longer, but still much too long for my case 😢 . My guess is, that it is colerated with `i18n`.

Config generated for my case looks like this:

```ts
const config = {
    sitemaps: {
        connections_1: {
            urls: async () => {
                const data = await fetch('...')

                return data.map(loc => ({
                        loc,
                        _i18nTransform: true
                }))
            }
        },
        connections_2: {
                // ... and so on
        },
    }
}
```

For now, I'll just stay at lower version, but I would appreciate help with this problem! 🙏

**Comment by harlan-zw** [comment]
Hey, could you confirm how / when the sitemap is generated?

Is this at build time (pre-rendered) or at runtime? If it's at runtime it may be related to https://github.com/nuxt-modules/og-image/issues/213#issuecomment-2143857858
