### ISSUE TITLE
When generating, ${BASE_URL}/sitemap.xml is being called

### ISSUE THREAD

**Issue by Guito** [nuxt-modules/sitemap#283]
I have just moved from nuxt-simple-sitemap to @nuxtjs/sitemap.

When using dev mode, the module works correctly, however, when I try to generate the application, this plugin is fetching http://127.0.0.1/sitemap.xml trying to generate sitemap.xml.

Why are we calling this URL? It crashes because it is returning a 504: timeout.

I have the global fetch modified so it points to my API, that's why there is the 127.0.0.1. Is there any solution for this apart from not modifying the global fetch?

**Comment by harlan-zw** [comment]
You should not be modifying the global fetch, there is no workaround for this within the module.

This will also break any other module needing to fetch.
