### ISSUE TITLE
TypeError: Could not load virtual:#sitemap/global-sources.mjs (imported by node_modules/@nuxtjs/sitemap/dist/runtime/nitro/sitemap/urlset/sources.mjs): Converting circular structure to JSON     --> starting at object with constructor 'Array'     --- index 4 closes the circle

### ISSUE THREAD

**Issue by mir1198yusuf** [nuxt-modules/sitemap#285]
Hello, I am getting this error after adding `@nuxtjs/sitemap` in `nuxt.config.ts`.
Version of `@nuxtjs/sitemap`  = `^5.1.5`.

```
export default defineNuxtConfig({
...
    sitemap: {
        urls: generateSitemap,
    },
...
})
```

and `generateSitemap` async function returns array of objects for sitemap.

**Comment by harlan-zw** [comment]
Can you post a sample of the data output? I don't think it's outputting the expected data.
