### ISSUE TITLE
"postinstall": "pnpm dev:prepare"    issue

### ISSUE THREAD

**Issue by rczdgbg** [nuxt-modules/sitemap#303]
![image](https://github.com/nuxt-modules/sitemap/assets/38928451/b87b1e1c-4d35-4795-8363-60e43e4d337b)

**Comment by Yizack** [comment]
Same here, I think packages should not have a `postinstal`l script, it was recently added in https://github.com/nuxt-modules/sitemap/commit/f6b31057ed1bfbf009e4e5e128f534557850459e

**Comment by harlan-zw** [comment]
cc: @shinGangan, I'll push up a hotfix

**Comment by harlan-zw** [comment]
Fixed in 5.3.2, thanks for reporting.

**Comment by shinGangan** [comment]
@harlan-zw , thanks for the correction 🙏

**Comment by shinGangan** [comment]
@rczdgbg , @Yizack , thank you for reporting!
