### ISSUE TITLE
如何添加额外的协议

### ISSUE THREAD

**Issue by freezyh** [nuxt-modules/sitemap#305]
例如：
`<?xml version="1.0"encoding="UTF-8" ?> 
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
xmlns:mobile="http://www.baidu.com/schemas/sitemap-mobile/1/"> 
<url> 
<loc>http://m.abc.com/index.html</loc> 
<mobile:mobiletype="mobile"/>
<lastmod>2009-12-14</lastmod>
<changefreq>daily</changefreq>
<priority>0.8</priority>
</url> `

</urlset> 
我想添加 urlset 中添加xmlns:mobile="http://www.baidu.com/schemas/sitemap-mobile/1/
在<url> 标签中添加<mobile:mobiletype="mobile"/>

 版本："@nuxtjs/sitemap": "^2.4.0"

**Comment by harlan-zw** [comment]
Hi, your best bet, for now, is to use the [sitemap:output](https://nuxtseo.com/sitemap/nitro-api/nitro-hooks#sitemapoutput) Nitro hook.

I can consider adding a nicer way to handle this in the future but I'm not familiar with this directive.

**Comment by freezyh** [comment]
文档找到配置方法了https://sitemap.nuxtjs.org/usage/sitemap-options/#xmlns-optional---string

**Comment by freezyh** [comment]
如果要添加<mobile:mobiletype="mobile"/>
`  sitemap: {
    xmlNs:
      'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:mobile="http://www.baidu.com/schemas/sitemap-mobile/1/"',
    // 默认的配置
    defaults: {
      mobile: 'mobile',
    }
}`

**Comment by harlan-zw** [comment]
I don't think this is something I want to support at this time using a module option. I've added for recipe for how to modify it on the docs.

### Modify Sitemap `xmlns` attribute

For some search engines, you may need to add a custom `xmlns` attribute to the sitemap. You can do this with a simple 
search and replace in the `sitemap:output` hook.

```ts [server/plugins/sitemap.ts]
import { defineNitroPlugin } from 'nitropack/runtime/plugin'

export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('sitemap:output', async (ctx) => {
    ctx.sitemap = ctx.sitemap.replace('<urlset ', '<urlset xmlns:mobile="http://www.baidu.com/schemas/sitemap-mobile/1/" ')
  })
})
```
