### ISSUE TITLE
i18n: How to generate dynamic urls per language?

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/sitemap#310]
I have an endpoint that generates urls for all my products:

nuxt.config:
```
sitemap: {
    sources: [
      process.env.NUXT_PUBLIC_API_URL + '/public/products/sitemap-urls',
    ],
  },
```

endpoint:
```ts
export default defineCachedEventHandler(async (event): Promise<SitemapUrl[]> => {
    const items = await useDb()...

    return items.map((item) => ({
         loc: `de/produkte/${getProductCleanUrl(item.name, item.company)}/${item.id}`,
         lastmod: item.lastUpdated.toISOString(),
    }));
});
```

But this generated the same urls for all languages, so they show up in `de-DE-sitemap.xml` and `en-GB-sitemap.xml` and `fr-FR-sitemap.xml`.

How can I generate urls per language?

UPDATE: Seems like it just works if I add to the same endpoint both `/de` and `/en` routes they get added to the corresponding sitemaps.

**Comment by harlan-zw** [comment]
Hi, glad you could figure this out.

The guide for this can be found at [Dynamic URLs with i18n](https://nuxtseo.com/sitemap/integrations/i18n#dynamic-urls-with-i18n), let me know if you have any further questions.

**Comment by MickL** [comment]
The docs dont say anything about it, maybe you want to add this information?

Also I was wondering if there is any interface for the handler to return, what I did to figure it out was trial and error :(

**Comment by harlan-zw** [comment]
I think this is intuitive enough not to document, I think the only thing that tripped you up was the missing leading slash which could be more considered a bug.

There is guidelines for the types on the [Dynamic URL Endpoint](https://nuxtseo.com/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint) page.

**Comment by MickL** [comment]
I think the whole docs were missing a few informations for dynamic urls in general, even before I added i18n. I just found out by trial and error.

My biggest question was: What does url endpoint need to return? There was no interface or explaination. In the end I found out by trial and error that I can just return an array of string and later it can also be an object with `loc` and `lastmod`. Is there not Interface?

**Comment by harlan-zw** [comment]
If you use any of the functions it tells you you'll have full typescript definitions of what to return.

Otherwise, just open the [Schema documentation](https://nuxtseo.com/sitemap/api/schema).

**Comment by MickL** [comment]
Oh now I understand, you mean the user should use `defineSitemapEventHandler()` instead of `defineEventHandler()`?

This wasnt clear for me. Personally I would argue that adding another eventHandler function creates an unnecessary abstraction. For example some users might want to use `defineEventHandler()` while others want to use `defineCachedEventHandler()`.

Checking `defineSitemapEventHandler()´ made me find the interface that I was looking for: `SitemapUrlInput` is what the handler should return. Unfortunately the package does not export this interface so it cant be used.

**Comment by harlan-zw** [comment]
You should use the asSitemapUrl composable,
