### ISSUE TITLE
i18n: How to disable indexing of custom route paths (translated route paths)

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/sitemap#311]
With nuxt/i18n comes the feature of [custom route paths](https://i18n.nuxtjs.org/docs/guide/custom-paths) which basically allows for translating the paths, e.g. 

```
products.vue

-> /en/products
-> /de/produkte
-> /es/productos
```

But how can I disable indexing for those paths all together? Right now I need to do:

```
'/products': {
   robots: false,
},
'/produkte': {
   robots: false,
},
'/productos': {
   robots: false,
}
```

But I would kinda imagine to use the route name instead which would be `products`.

Btw. setting `robots: false` as [said in the docs](https://nuxtseo.com/sitemap/guides/filtering-urls) has no effect. I always need to set `sitemap: false`.

**Comment by harlan-zw** [comment]
I think you have found the best solution for the time being. Ideally, you should be able to provide the default locale path as an exclude and it would propagate to the other paths.

```ts
export default defineNuxtConfig({
  sitemap: {
    exclude: ['/products']
  }
})
```

I'll leave this issue open to investigate the robots issue and the above.

**Comment by MickL** [comment]
I tried every possible option with no success:

```ts
export default defineNuxtConfig({
  sitemap: {
    exclude: ['/products', 'products', 'products/index']
  }
})
```

It would be great if we could use the route name and then all the translated routes are excluded. E.g. `/product/[id]` has the route name `products-id` (visible in the devtools). Otherwise imagine to have 10 routes to exclude and 10 languages, this would already result in 100 routeRoules within nuxt.config.ts.

**Comment by MickL** [comment]
Support for custom route paths would be amazing :)

**Comment by harlan-zw** [comment]
Hi, I've pushed up a fix for the `robots` route rules and I've also added support for the i18n custom route paths.

Both will be available in v6 soon.

**Comment by MickL** [comment]
Amazing!! :)

What do you mean exactly by "support for the i18n custom route paths"? Means I can add the route name instead of route path? Or how does it work?

**Comment by harlan-zw** [comment]
So it should be pretty intuitive once you need to exclude something, say we have a i18n pages config as follows:

```ts
pages: {
        'about': {
          en: '/about',
          fr: '/a-propos',
        },
        'services/index': {
          en: '/services',
          fr: '/offres',
        },
        'services/development/index': {
          en: '/services/development',
          fr: '/offres/developement',
        },
        'services/development/app/index': {
          en: '/services/development/app',
          fr: '/offres/developement/app',
        },
        'services/development/website/index': {
          en: '/services/development/website',
          fr: '/offres/developement/site-web',
        },
        'services/coaching/index': {
          en: '/services/coaching',
          fr: '/offres/formation',
        },
        'some-mismatched-key': {
          en: '/foo',
          fr: '/bar',
        }
      }
```

If we do

```ts
export default defineNuxtConfig({
  sitemap: {
    exclude: ['/about']
  }
})
```

It will then generate:
- /about
- /a-propos

It will also match the default locale keys, so if we have `en` as the default and I pass in this

```ts
export default defineNuxtConfig({
  sitemap: {
    exclude: ['/foo']
  }
})
```

It will then generate:
- /foo
- /bar
