### ISSUE TITLE
[Bug] 5xx if too many pages & languages

### ISSUE THREAD

**Issue by fouss** [nuxt-modules/sitemap#312]
Hey, I have a problem with my sitemap : 
- my website have ~320pages translated in 24 languages (~7600 pages)
- 99% of these pages are dynamique
- I18n is handle by i18n nuxt module
- All my pages are available for all locales

First I created an endpoint returning the list of all my path "unprefixed" (in the default language), it worked perfectly but only the "en-us" sitemap was full.
So i updated my endpoint to return all my path unprefixed (for default language) + prefixed 
→ the sitemap index is always OK but when i try to open one the site localized sitemap, nothing happened and it finally crash.

I tried with less languages (so less path) it's slow, but at least, it worked...

Is there anything i do in a wrong way ?

Thanks

**Comment by harlan-zw** [comment]
The [i18n logic](https://github.com/nuxt-modules/sitemap/blob/main/src/runtime/nitro/sitemap/urlset/i18n.ts#L11) probably needs some optimization work, feel free to send a PR if you see any areas for improvements.

**Comment by harlan-zw** [comment]
A fix will be available in v6.0.0 which should be out soon.
