### ISSUE TITLE
Homepage down

### ISSUE THREAD

**Issue by ManuelTS** [nuxt-modules/sitemap#315]
Coming from the github link

https://nuxtseo.com/sitemap/getting-started/installation 

gives me currently:

![image](https://github.com/user-attachments/assets/e76e342b-81ec-4807-a3ba-9d1365e2604a)

but if I go to nuxtseo.com and then try to access the sitemap module, the error page is different

![image](https://github.com/user-attachments/assets/ab1158c5-e1fc-4d47-9179-e51f4973605e)

maybe this helps to detect the problem faster. But I guess, the different error page is just differnt http status code handling

**Comment by harlan-zw** [comment]
Thanks for flagging this, should be fixed now.
