### ISSUE TITLE
Dynamic URLs with i18n will not automatically add a language prefix

### ISSUE THREAD

**Issue by Red-Asuka** [nuxt-modules/sitemap#316]
Using the latest version of `@nuxtjs/sitemap: 5.3.4`, I found that when configuring dynamic URLs for a single language with i18n, the language prefix is not automatically added even though the i18n strategy is set to prefix. While configuring dynamic URLs for all languages works as expected, this behavior does not match the example provided in the [documentation](https://nuxtseo.com/sitemap/integrations/i18n#_sitemap). I’m not sure if this is a bug.

```ts
const sitemap: NuxtConfig['sitemap'] = {
  defaults: {
    changefreq: 'weekly',
  },
  exclude: [
    ...excludeRoutes,
  ],
  urls: [
    { loc: '/use-cases/smart-water', _sitemap: 'zh' },
    { loc: '/use-cases/smart-parking', _sitemap: 'zh' },
    { loc: '/use-cases/digital-twin', _sitemap: 'zh' },
    { loc: '/use-cases/sap', _sitemap: 'zh' },
  ],
}
```

<img width="835" alt="image" src="https://github.com/user-attachments/assets/fce52e32-da08-4bf7-8329-951d277df2b0">

<img width="539" alt="image" src="https://github.com/user-attachments/assets/23e4fad2-9dc2-4e3c-898c-ec3e86dfe4a1">

**Comment by harlan-zw** [comment]
Hi, you will stop the i18n prefixing when you manually specify the `_sitemap` that the URL belongs to. You should omit this if you want it to split it for you.

**Comment by Red-Asuka** [comment]
Thank you for your quick response. I understand now that `_sitemap` is used to specify which language’s sitemap a URL should appear on. In this case, I will set `loc` to a language-prefixed URL, similar to how the other data are structured in `debug.json`.

However, I still have one question: if a page is only available in one language, do I still need to set `alternatives`?

Thank you very much!

**Comment by Red-Asuka** [comment]
I modified the configuration, and now it is working well.

<img width="971" alt="image" src="https://github.com/user-attachments/assets/d824fae3-a415-4cdf-8334-34df560a76f8">
<img width="383" alt="image" src="https://github.com/user-attachments/assets/93772e76-dcd1-4c73-b7fb-ed26a20598ab">
