### ISSUE TITLE
False multi-sitemap warning

### ISSUE THREAD

**Issue by EmilRiedeman** [nuxt-modules/sitemap#317]
I get the warning that I provided a `sitemap.sources` while using multiple-sitemaps, but I did not provide it:
```ts
export default defineNuxtConfig({
  // ...
  sitemap: {
    sitemaps: {
      pages: {
        includeAppSources: true,

        exclude: [
          '/account/**',
        ]
      },
      index: [
        {
          sitemap: (process.env.NUXT_PUBLIC_API_URL ?? 'http://localhost:8000/api/v1') + '/sitemap.xml'
        }
      ]
    }
  }
}
  ```
  
  The sitemap generating seems to be working fine for me.
  
 It gave the warning with commit 32b9f86 after resolving issue #287

**Comment by harlan-zw** [comment]
Can you confirm which version you're using, it was fixed in https://github.com/nuxt-modules/sitemap/releases/tag/v5.3.3 (as far as I know).
