### ISSUE TITLE
Sitemap URL returns 500 error when accessed directly

### ISSUE THREAD

**Issue by shehab267** [nuxt-modules/sitemap#318]
The sitemap URL (https://nuxtseo.com/sitemap/getting-started/installation) returns a 500 Internal Server Error when accessed directly in the browser. However, it can be accessed manually through the website (https://nuxtseo.com/).

Steps to reproduce:
1. Copy https://nuxtseo.com/sitemap/getting-started/installation and paste into browser
2. Observe 500 error
3. Navigate to https://nuxtseo.com/ and access sitemap from there
4. Observe sitemap loads correctly

Steps:
1. Access https://nuxtseo.com/sitemap/getting-started/installation
2. Observe 500 error

**Comment by harlan-zw** [comment]
Thank you for the issue, this should be fixed. It's an issue with the latest Nuxt patch so have pinned to a prior version.
