### ISSUE TITLE
help: sitemap-lastmod feature is forced to transfer iso type

### ISSUE THREAD

**Issue by FairyFanFan** [nuxt-modules/sitemap#327]
### 📚 What are you trying to do?

i wanna define [lastmod] value in my own time type

### ℹ️ Additional context

nuxt 2
nuxtjs-sitemap  v2.4.0

**Comment by harlan-zw** [comment]
Hi, can you please make an issue on https://github.com/nuxt-community/sitemap-module, this repo is only for the Nuxt v3 version.

**Comment by FairyFanFan** [comment]
> Hi, can you please make an issue on https://github.com/nuxt-community/sitemap-module, this repo is only for the Nuxt v3 version.

yep thx i have already done that
