### ISSUE TITLE
fix: articleModifiedTime does not work

### ISSUE THREAD

**Issue by alimozdemir** [nuxt-modules/sitemap#328]
### 🐛 The bug

It looks like articleModifiedTime on page seo definition does not work, it is not setting it even after build the website.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-xuegzl?file=pages%2Findex.vue

### 🌈 Expected behavior

It should set lastmod for that page.

**Comment by harlan-zw** [comment]
This appears to be working in the latest version https://stackblitz.com/edit/nuxt-starter-t5bfrg?file=.output%2Fpublic%2Fsitemap.xml
