### ISSUE TITLE
multiple-sitemaps warning shows up even if `sources` not exists in nuxt.config.ts

### ISSUE THREAD

**Issue by HADB** [nuxt-modules/sitemap#332]
### 🐛 The bug

This warning will show even if there is no sources config in sitemap.

``` 
WARN  You are using multiple-sitemaps but have provided sitemap.sources in your Nuxt config. This will be ignored, please move it to the child sitemap config.  
```

There will be a default `sources` key which causes the warning always shows up.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-oqz8oh?file=nuxt.config.ts

### 🌈 Expected behavior

Not showing this warning if there's no `sources` config in nuxt.config.ts

**Comment by madebyfabian** [comment]
Having the exact same issue and were also able to reproduce it:
https://stackblitz.com/~/github.com/madebyfabian/seo-reprod

**Comment by harlan-zw** [comment]
Yes please 🙏 otherwise I'll look at this next time I'm working on the module
