### ISSUE TITLE
help: How to remove trailing slash from homepage url

### ISSUE THREAD

**Issue by AleeeKoi** [nuxt-modules/sitemap#335]
### 📚 What are you trying to do?

I need to remove the trailing slash from the homepage location into the sitemap, others location are working fine.
So for example, I need to replace the location `https://example.com/` with `https://example.com`.

Other locations are working without errors, also canonical url and internal links are compiled without trailing slashed.

### ℹ️ Additional context

The sitemap is generated building with nitro using the cloudflare pages preset.

**Comment by harlan-zw** [comment]
Both of these are equivalent, for semantic reasons I prefer having the trailing slash on the root domain and it can help avoid some issues.

See https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

> Rest assured that for your root URL specifically, https://example.com is equivalent to https://example.com/ and can't be redirected even if you're Chuck Norris.

**Comment by AleeeKoi** [comment]
Hi @harlan-zw , the problem is that the `useLocaleHead` method returns a canonical url without the trailing slash even fort the home page. I understand that this method is not part of your lib, but is there a solution to make them equal?
Thanks.

**Comment by harlan-zw** [comment]
It won't be an issue if the canonical here doesn't match as they are the same thing in Google's eyes. Are you seeing a warning from any google tooling?

**Comment by AleeeKoi** [comment]
Yep, try to test core web vitals, in the SEO section you will see the issue. Google prefers the home URL with trailing slash, Google redirects the base path without trailing slash to the version with it.For now I have manually update the canonical and alternatives hreflang adding the trailing slash for the the homepage only.Is there a way to do it better?ThanksIl giorno 13 ago 2024, alle ore 06:57, Harlan Wilton ***@***.***> ha scritto:﻿
It won't be an issue if the canonical here doesn't match as they are the same thing in Google's eyes. Are you seeing a warning from any google tooling?

**Comment by harlan-zw** [comment]
I'd suggest for the time being to use the Nuxt SEO module which will override the canonical to the correct path. Otherwise I'll need to look into this further when I have some free time.

**Comment by harlan-zw** [comment]
Important to note that the HTTP spec says that an empty path should be converted to a `/` so it's more so an issue with the Nuxt I18n module, however again they are equivalent.

> If  the abs_path is not present in the URL, it MUST be given as "/" whe used as a Request-URI for a resource (section 5.1.2).

https://www.rfc-editor.org/rfc/rfc2616#section-3.2.2
