### ISSUE TITLE
help: how to implement trailing slash feature for URLs in sitemap.xml?

### ISSUE THREAD

**Issue by projectfreak** [nuxt-modules/sitemap#341]
### 📚 What are you trying to do?

I have a sitemap.xml generated, but I notice that apart from the root URL, all other URLs do not have a trailing slash. I would like to activate this - as before - using something like trailingSlash=true.

### 🔍 What have you tried?

The dynamic structure of the URLs *with* trailing slash also leads to a listing *without* trailing slash in the sitemap.xml.

**Comment by harlan-zw** [comment]
Hi @projectfreak, by default trailing slashes are removed. If you'd like to enable trailing slashes please follow the docs here: https://nuxtseo.com/sitemap/getting-started/installation

**Comment by projectfreak** [comment]
Oh, thank you so much!
I had already read that, but it probably didn't work because of another error in my setup. Now it works as desired.
Thanks for the quick help!
