### ISSUE TITLE
fix: Warning:  Export "useNitroApp" was reexported through module

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/sitemap#342]
### 🐛 The bug

I updated to latest `@nuxtjs/seo` `2.0.0-rc.18` which is using @nuxtjs/sitemap `^6.0.0-beta.2` and now get an error when building using `NITRO_PRESET=cloudflare-pages nuxt build`:

```
Building Nuxt Nitro server (preset: cloudflare-pages)

Export "useNitroApp" of module "../../node_modules/nitropack/dist/runtime/app.mjs" was reexported through module "../../node_modules/nitropack/dist/runtime/index.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.

Either change the import in "../../node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap_index.xml.js" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

**Comment by harlan-zw** [comment]
This is a warning I believe not an error

**Comment by MickL** [comment]
You are right, the error came from `nuxt-og-image`
https://github.com/nuxt-modules/og-image/issues/257

**Comment by rcerljenko** [comment]
yep.. same

![{A8FFD855-B550-4770-A6DB-4FB16ADE88D4}](https://github.com/user-attachments/assets/41a98ab2-af66-4987-a8e6-837971143418)

**Comment by mohammadGh** [comment]
I'm getting this warning too.

```
Nuxt 3.13.2 with Nitro 2.9.7 

This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/.../sitemap@6.0.0_h3@..." to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
```

**Comment by vratskyi** [comment]
![Image](https://github.com/user-attachments/assets/0e7ec2a5-9bff-4991-9990-94bbcc580a09)

Same **[WARN]**

If I disable @nuxtjs/sitemap everything becomes normal, apparently I will have to give up @nuxtjs/sitemap for a while, and generate sitemap using third-party services, how it is not convenient guys :(

**Comment by harlan-zw** [comment]
This is a false-positive warning generated by Nitro. It is completely safe to ignore.

I can't change it without breaking compatibility with Nitro v3
