### ISSUE TITLE
help: lastmod ISO8601 format

### ISSUE THREAD

**Issue by brewaa** [nuxt-modules/sitemap#343]
### 📚 What are you trying to do?

Hi,

I'm using: "@nuxtjs/sitemap": "^5.3.2".

I have my dates in W3C datetime encoding format:

_2024-08-20T17:56:10+10:00_

The output in the sitemap is:

_2024-08-20T07:56:10Z_

This seems to be incorrect.

Is there a way to have the sitemap just output the exact date value I give it?

I think this line may be incorrect:

https://github.com/nuxt-modules/sitemap/blob/82f687cd288e00d1c8c729f201590c0e10193113/src/runtime/nitro/sitemap/urlset/normalise.ts#L122

If the date string has a plus sign you should probably just accept it and try to parse that value.

Any help will be much appreciated.

**Comment by brewaa** [comment]
The Zulu time may be correct, so forgive me if I've raised a non issue.

**Comment by harlan-zw** [comment]
Hi, please format it to one of the two:
- `2005-02-21`
- `2005-02-21T18:00:15+00:00`
