### ISSUE TITLE
fix: Sitemap is completely empty

### ISSUE THREAD

**Issue by MickL** [nuxt-modules/sitemap#344]
### 🐛 The bug

Using latest `@nuxtjs/seo 2.0.0-rc.17` that is using `@nuxtjs/sitemap 6.0.0-beta.2` the sitemap is completely empty, does not contain a single link.

Downgrading to `@nuxtjs/seo 2.0.0-rc.16` that uses `@nuxtjs/sitemap 5.3.5` everything works again.

### 🛠️ To reproduce

Sorry I dont have the time, I hope you can reproduce

**Comment by MickL** [comment]
`2.0.0-rc.16` sets noindex, nofollow to ALL routes. Going back to rc.11

**Comment by JordanchoEftimov** [comment]
I can confirm that using the latest `@nuxtjs/seo` was making the sitemap empty. I downgraded as stated above and now the sitemap words.

**Comment by vaddenz** [comment]
Same here, took hours to figure this out. Very annoying.

**Comment by harlan-zw** [comment]
Please use the latest Nuxt SEO. The bug was related to the a broken nuxt robots version.

**Comment by harlan-zw** [comment]
Would it be possible to provide a [minimal reproduction](https://nuxtseo.com/robots/getting-started/installation)? I've tried to cover as many test cases as I could but it's possible I missed something

**Comment by MickL** [comment]
I just deleted node_modules folder and lock file and now it seems to work, thanks!
