### ISSUE TITLE
help: how to custom path multiple sitemap?

### ISSUE THREAD

**Issue by datisekai** [nuxt-modules/sitemap#347]
### 📚 What are you trying to do?

` sitemap: {
    sitemaps: {
      blogs: {
        sources: ["/api/__sitemap__/blogs"],
      },
      pages: {
        sources: ["/api/__sitemap__/pages"],
      },
      articles: {
        sources: ["/api/__sitemap__/articles"],
      },
      galleries: {
        sources: ["/api/__sitemap__/galleries"],
      },
    },
  },`
  
I want custom paths.
For example:
- from /blogs-sitemap.xml to /sitemap/blogs.xml
- from /pages-sitemap.xml to /sitemap/pages.xml
- from /articles-sitemap.xml to /sitemap/articles.xml
- from /galleries-sitemap.xml to /sitemap/galleries.xml

**Comment by harlan-zw** [comment]
I'm not exactly sure what you're asking for but if you use Nuxt Sitemap v6 beta it uses the paths on the right.

**Comment by datisekai** [comment]
> I'm not exactly sure what you're asking for but if you use Nuxt Sitemap v6 beta it uses the paths on the right.

thanks, my problem is solved in v6
