### ISSUE TITLE
fix: `Module '"#imports"' has no exported member 'asSitemapUrl'`

### ISSUE THREAD

**Issue by guy-confetti** [nuxt-modules/sitemap#355]
### 🐛 The bug

- production build fails when importing `asSitemapUrl` or `defineSitemapEventHandler`
- dev build works, although the import shows an error on stackblitz

### 🛠️ To reproduce

https://stackblitz.com/edit/github-qjnbzv?file=server%2Fapi%2Fsitemap.ts

### 🌈 Expected behavior

according to the [docs](https://nuxtseo.com/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint), should be importable from `#imports`

**Comment by harlan-zw** [comment]
Hi, thanks for the reproduction.

Can you try doing `nuxi upgrade --clean` it might be a cache / dependency conflict issue.

In terms of Stackblitz I think that's a bug on their end, for some reason the don't respect the tsconfig.json in the server directory.

**Comment by felixgabler** [comment]
Hi! I get the same issue, both locally and on production. `nuxt upgrade --clean` did not help, unfortunately.

**Comment by harlan-zw** [comment]
Please check you have a tsconfig.json in your server folder pointing to the nitro types 

```
{
  "extends": "../.nuxt/tsconfig.server.json"
}
```

**Comment by typeoneerror** [comment]
> Please check you have a tsconfig.json in your server folder pointing to the nitro types
> 
> {
>   "extends": "../.nuxt/tsconfig.server.json"
> }

Getting the same error with this file in /server

**Comment by harlan-zw** [comment]
Please see the latest docs for type best practice https://nuxtseo.com/docs/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint

**Comment by typeoneerror** [comment]
> Please see the latest docs for type best practice https://nuxtseo.com/docs/sitemap/guides/dynamic-urls#_2-create-your-own-endpoint

Thanks, @harlan-zw! If anyone else is getting stuck here, the fix for me was 
```
npx nuxt prepare
```

To create the necessary tsconfig files that were missing.
