### ISSUE TITLE
feat: Dynamic chunking

### ISSUE THREAD

**Issue by ronenteva** [nuxt-modules/sitemap#361]
### 🆒 Your use case

Following #360 and #265, as user needs can become complicated and specific, I suggest supporting an api endpoint for dynamic chunking.

### 🆕 The solution you'd like

```
export default defineNuxtConfig({
  sitemap: {
    sitemapsSource: '/api/sitemap-index`
  }
})
```
```
export default defineSitemapIndexEventHandler(async () => {
  return categories.map(category=>{
    return locales.map(locale=>{
      return pages.map(page=>{
        return {
          sitemap: `sitemap-${locale}-${category}-${page}`,
          source: `...`
        }
      })
    })
  })
```

**Comment by harlan-zw** [comment]
Thanks for the suggestion, I don't plan on adding any support for this outside of the Nitro hook which should let you customize the output however you like.

See https://nuxtseo.com/sitemap/nitro-api/nitro-hooks#sitemapindex-resolved

**Comment by ronenteva** [comment]
Oh perfect, that's definitely good enough, thanks!
