### ISSUE TITLE
help: Want to understand how i can give custom names to the multiple sitemap generated from dynamic data feteched with defaultSitemapsChunkSize value set to 500 urls in each sitemap

### ISSUE THREAD

**Issue by kherapu** [nuxt-modules/sitemap#364]
### 📚 What are you trying to do?

I am not sure how to set custom names to multiple sitemap xml files generated

**Comment by morgota199** [comment]
same problem...

**Comment by harlan-zw** [comment]
This is not currently supported, please track here https://github.com/nuxt-modules/sitemap/issues/265.
