### ISSUE TITLE
fix: nuxt-i18n-micro route generation

### ISSUE THREAD

**Issue by s00d** [nuxt-modules/sitemap#367]
### 🐛 The bug

Hello,

I’ve gotten around to testing, and overall, the module works, but it currently only generates routes for the default locale. The issue is that my module handles route generation differently. For multiple locales, it creates a single route, for example:

`/:locale(de|ja)/page`

So it bundles all locales into one route, which prevents large bundles from being created, unlike in i18n. In order for everything to work properly, the `deepForEachPage` method needs to be adjusted.

Here’s a possible solution:

```javascript
function deepForEachPage(pages, callback, routesNameSeparator, fullpath = null, depth = 0) {
  pages.forEach((page) => {
    let currentPath;
    if (page.path.startsWith("/")) {
      currentPath = page.path;
    } else {
      currentPath = page.path === "" ? fullpath : `${fullpath.replace(/\/$/, "")}/${page.path}`;
    }

    const localePattern = /\/:locale\(([^)]+)\)/;
    const match = localePattern.exec(currentPath);


    if (match) {
      const locales = match[1].split("|");
      locales.forEach((locale) => {
        let subPage = { ...page };
        const localizedPath = currentPath.replace(localePattern, `/${locale}`);
        subPage.name += routesNameSeparator + locale
        subPage.path = localizedPath
        callback(subPage, localizedPath || "", depth);
      });
    } else {
      callback(page, currentPath || "", depth);
    }

    if (page.children) {
      deepForEachPage(page.children, callback, routesNameSeparator, currentPath, depth + 1);
    }
  });
}
```

In this implementation, if the route contains `:locale`, it extracts the locale from the route and converts the routes into a default format similar to i18n. I’ve added a `routesNameSeparator` to the method to handle naming.

I didn’t create a pull request since it’s probably better for you to review how this should be properly integrated.

https://github.com/s00d/nuxt-i18n-micro/issues/11

### 🛠️ To reproduce

https://github.com/s00d/nuxt-i18n-micro/tree/main/test/fixtures/sitemap

### 🌈 Expected behavior

...

**Comment by harlan-zw** [comment]
Thanks for your help with this, I've made the fix here https://github.com/nuxt-modules/sitemap/commit/7a4946023072237d34c7acbdd2b6ec24dea8e5e5

I'll push this up in a release but let me know if you spot any issues.
