### ISSUE TITLE
help: How to automatically update a sitemap

### ISSUE THREAD

**Issue by w156ww** [nuxt-modules/sitemap#376]
### 📚 What are you trying to do?

Hello
I want to update the content of the sitemap regularly after the Nuxt project is released. At present, looking at the documentation, it seems that there is no way to update regularly, and the sitemap can only be dynamically generated through the deployment stage.
Because the project contains a large number of dynamic routes, add data from the CMS system and generate new routes. Therefore, I want to update the sitemap without redeploying the nuxt project.

Is there any way to do it?

This is my current sitemap example：
```javascript
sitemap: {
        autoLastmod: true,
        async urls() {
            const {data, code} = await fetch(`${process.env.NUXT_PUBLIC_BASE_URL}/api/getDynamicRouteUrl`).then(res => res.json())
            if (code === 0) {
                return data.map(item => {
                    return {
                        loc: `${process.env.NUXT_PUBLIC_SITE_URL}/${item.handle}`,
                        lastmod: item.product_in_time
                    }
                })
            }
        },
    },
``` 

### 🔍 What have you tried?

I have checked the official documents and the third-party community, but I can't find the answer I want. If there is anything missing, please let me know. Thanks！

### ℹ️ Additional context

"@nuxtjs/sitemap": "^6.1.1",
"nuxt": "^3.13.0",

**Comment by harlan-zw** [comment]
Hi, see here https://nuxtseo.com/docs/sitemap/guides/dynamic-urls

**Comment by w156ww** [comment]
> 你好，请参见此处https://nuxtseo.com/docs/sitemap/guides/dynamic-urls

Thanks for the reply, I have read the content here. Can you think that if you use source to set the sitemap data, you can dynamically update it, but the urls method will not work? Another point, how to determine the update frequency? Is it associated with the cacheMaxAgeSeconds attribute?

**Comment by w156ww** [comment]
OK, I seem to know what's going on. Through the method configuration of source, the interface is re-called every time you visit the sitemap, while urls is directly obtained in the deployment phase after hardcode/hard coding.
Thanks for the help.
