### ISSUE TITLE
help: Import types from runtime/types.d.ts

### ISSUE THREAD

**Issue by MarijnFK** [nuxt-modules/sitemap#377]
### 📚 What are you trying to do?

How can i import the types from the runtime? I'd like to use `SitemapUrl` or `SitemapUrlInput`.

### 🔍 What have you tried?

tried importing directly from @nuxtjs/sitemap/dist/runtime/types

**Comment by harlan-zw** [comment]
Hi, thanks for the question.

In 6.1.4 you can import the types from `#sitemap/types`. I've updated the docs to show this.
